// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ItemID    int64     `json:"item_id"`
	UserID    int64     `json:"user_id"`
	ItemName  string    `json:"item_name"`
	Quantity  int64     `json:"quantity"`
	Price     int64     `json:"price"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Order struct {
	OrderID     int64       `json:"order_id"`
	UserID      int64       `json:"user_id"`
	ItemID      int64       `json:"item_id"`
	Status      string      `json:"status"`
	PaymentLink pgtype.Text `json:"payment_link"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type User struct {
	UserID            int64     `json:"user_id"`
	UserName          string    `json:"user_name"`
	FirstName         string    `json:"first_name"`
	LastName          string    `json:"last_name"`
	Email             string    `json:"email"`
	Password          string    `json:"password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	IsEmailVerified   bool      `json:"is_email_verified"`
	Role              string    `json:"role"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}
