user:
	@protoc --go_out=./api/user_service --go_opt=paths=source_relative \
		--go-grpc_out=./api/user_service --go-grpc_opt=paths=source_relative \
	 	./proto/user.proto

item:
	@protoc --go_out=./api/user_service --go_opt=paths=source_relative \
		--go-grpc_out=./api/user_service --go-grpc_opt=paths=source_relative \
	 	./proto/user.proto

order:
	@protoc --go_out=./api/user_service --go_opt=paths=source_relative \
		--go-grpc_out=./api/user_service --go-grpc_opt=paths=source_relative \
	 	./proto/user.proto
